### ISSUE TITLE
wstock query name(中文的时候没有相关记录)

### ISSUE THREAD

**Issue by wodog** [hellopao/wstock#1]
![image](https://cloud.githubusercontent.com/assets/11365898/11607039/94dc71e6-9b72-11e5-8328-6cd682802164.png)
如图，我先query中文的时候没有相关记录，随后我再query该中文的转码后便有了

**Comment by wayne0423** [comment]
碰到同样的问题；中文参数没有Encode,导致key乱码

**Comment by hellopao** [comment]
@wodog  @wayne0423  解决了，名称加了encode
